
build_ffi: priv/ffi_es6_builtins.js
	npm run babel

build_parse_transform: src/*.erl src/*.hrl build_ffi
	./rebar3 compile
	# Ok now it's time to bootstrap IO
	./rebar3 escriptize
	./erlscripten -s _build/default/lib/erlscripten/ebin/erlang_io.beam -o priv/support/src/Erlang/IO.purs

build_transpilation_tests: build_parse_transform transpilation_tests/*.erl
	echo "Building transpilation_tests"
	ls transpilation_tests | grep "erl" | xargs -I ARG erlc -pa _build/default/lib/erlscripten/ebin transpilation_tests/ARG

transpilation_tests: build_transpilation_tests transpilation_tests/Main.purs
	cp transpilation_tests/Main.purs autogenerated_transpilation_tests/test
	cd autogenerated_transpilation_tests && spago test

erlscripten: build_parse_transform
	./rebar3 escriptize

compatability_benchmark: erlscripten
	ls /usr/lib/erlang/lib/stdlib-3.13.2/ebin | grep beam | xargs -IARG ./erlscripten -s /usr/lib/erlang/lib/stdlib-3.13.2/ebin/ARG -o test.purs | grep stdlib


