
-module(autoimport).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

%% API
-export([]).

make_tuple(_,_,_) -> ok.

test_autoimports() ->
  ok = make_tuple(0.0, 1.0, 2.0),
  {} = erlang:make_tuple(0, 0, []),
  ok.
