-module(binaries).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

test_build_empty() ->
    <<>>.
test_build_single() ->
    <<1>>.
test_build_multi() ->
    <<1,2,3>>.
test_build_string() ->
    <<"XD">>.
test_build_sub() ->
    <<<<1,2,3>>/binary>>.
test_build_float() ->
    <<1.0/float>>.
test_build_mixed() ->
    <<"XD",1,2,<<3,4>>/binary,5/float>>.

test_build_int_size() ->
    <<1:32>>.
test_build_int_size_unit() ->
    <<1:4/unit:8>>.
test_build_int_endian_little() ->
    <<1:32/little>>.
test_build_int_underflow() ->
    <<-1>>.
test_build_int_overflow() ->
    <<256>>.

test_build_string_size_unit() ->
    <<"XD":2/unit:8>>.

test_build_bin_size() ->
    <<<<1,2,3>>:2/binary>>.
test_build_bin_unit() ->
    <<<<1,2,3>>:16/binary-unit:1>>.

test_build_float_32() ->
    <<1:32/float>>.
test_build_float_32_unit() ->
    <<1:4/float-unit:8>>.
test_build_float_little() ->
    <<1/float-little>>.


