-module(circular_one).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

%% API
-export([]).

one() ->
  hello_from_module_one.

two() ->
  circular_two:two().
