
-module(comparator).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

-export([]).

test_comp1() ->
  false = x < 0,
  true = x > 0,
  ok.
