-module(onload).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

%% API
-export([]).

-on_load(thonk/0).

thonk() ->
  io:format("Hello from onload callback!\n"),
  ok.

get_hehe() ->
  hehe.
