-module(ordering).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

test_ordering_1() ->
    try
        [false = true, throw(probe)]
    catch error:{badmatch, true} ->
            ok
    end.

test_ordering_2() ->
    try
        [begin false = true end, begin throw(probe) end]
    catch error:{badmatch, true} ->
            ok
    end.

boom() ->
    throw(boom).
kaboom() ->
    throw(kaboom).
ok() ->
    ok.
test_ordering_3() ->
    try
        [ ok()
        , boom()
        , kaboom()
        , ok()
        ]
    catch boom ->
            ok;
          Bad -> Bad
    end.
