
-module(partiality).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

-export([]).

test_list_deconstruct() ->
  case [] of
    [H|_] -> H;
    [] -> hmm
  end,
  ok.

test_string_pattern("12345") ->
  ok.

test_empty_list() ->
  [] = lists:seq(1, 0),
  ok.
