-module(scoping).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

test_scope_1() ->
    [begin true = true end, begin false = false end],
    ok.

test_scope_2() ->
    [true = true, false = false],
    ok.
