
-module(string_escape).
-erlscripten_output(autogenerated_transpilation_tests).
-compile({parse_transform, erlps_parse_transform}).
-compile(nowarn).
-compile(export_all).

-export([]).

%% Stress the transpiler with weird strings :P
test_01() -> "\b".
test_02() -> "\d".
test_03() -> "\e".
test_04() -> "\f".
test_05() -> "\n".
test_06() -> "\r".
test_07() -> "\s".
test_08() -> "\t".
test_09() -> "\v".
test_10() -> "\1".
test_11() -> "\11".
test_12() -> "\111".
test_13() -> "\0xFF".
test_14() -> "\0xff".
test_15() -> "\0x{a}".
test_16() -> "\^a".
test_17() -> "\^f".
test_18() -> "\^z".
test_19() -> "\^A".
test_20() -> "\^F".
test_21() -> "\^Z".
test_22() -> "\'".
test_23() -> "\"".
test_24() -> "\\".
test_25() -> "żółć".
