%%%-------------------------------------------------------------------
%%% @author radek
%%% @copyright (C) 2020, <COMPANY>
%%% @doc
%%%
%%% @end
%%% Created : 26. Okt 2020 10:59
%%%-------------------------------------------------------------------
-module(playground).
-author("radek").
-erlscripten_output(autogenerated).
-compile({parse_transform, erlscripten}).
-compile(nowarn).
-compile(export_all).

f(X) ->
    ok.

f() ->
    f(1),
    f(2).
