%%%-------------------------------------------------------------------
%%% @author radek
%%% @copyright (C) 2020, <COMPANY>
%%% @doc
%%%
%%% @end
%%% Created : 26. Okt 2020 10:59
%%%-------------------------------------------------------------------
-module(playground).
-author("radek").
-erlscripten_output(autogenerated).
-compile({parse_transform, erlscripten}).
-compile(nowarn).
-compile(export_all).

test() ->
    case 123123123 of
	true ->
	    444;
	false ->
	    888888
    end.
