%%%-------------------------------------------------------------------
%%% @author radek
%%% @copyright (C) 2020, <COMPANY>
%%% @doc
%%%
%%% @end
%%% Created : 26. Okt 2020 10:59
%%%-------------------------------------------------------------------
-module(simple_test).
-author("radek").
-erlscripten_output(autogenerated).
-compile({parse_transform, erlscripten}).
-compile(nowarn).

%% API
-export([]).

ident(X) -> X.

unify(X, X) -> ok.

%%clause(x) -> ok;
%%clause(y) -> ko.
%%
%%tuple({X, X}) -> ok.
%%tuple({{X, X}, {X, X, X}}) -> xd.
%%
%%cons([H|T]) -> ok;
%%cons([H|[H|G]]) -> ok.
%%
%%maps(#{}) -> ok;
%%maps(#{dupa := X, pupa := X}) -> ok.